# ANSIBLE PLAYBOOK FOR DEPLOYING A PYTHON FLASK APPLICATION

-
  name: Deploy a web application
  hosts: target1
  tasks:
    - name: ping on the target server
      ping:

    - name: Install Python dependecies
      apt: name={{ item }} state=present
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip