# ANSIBLE PLAYBOOK FOR DEPLOYING A PYTHON FLASK APPLICATION

-
  name: Deploy a web application
  hosts: all
  tasks:
    - name: ping on the target server
      ping:

    - name: Install Python && its dependecies
      apt: name={{ item }} state=present
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
        - python3-apt
    
    - name: Install MySQL 
      apt: name={{ item }} state=present
      with_items:
        - mysql-server
        - mysql-client
    
    - name: Start the Service MySQL
      service: 
        name: mysql
        state: started
        enabled: yes
    
    # - name: install pip3
    #   apt: name=python3-pip  state=present 
    
    # - name: Make sure pymysql is present
    #   pip:
    #     name: pymysql
    #     state: present

    - name: Create Database
      mysql_db:
        name: employee_db
        state: present
        #target: /tmp/employee_db.sql
    
    - name: Create User
      mysql_user: 
        name: db_user
        password: Passw0rd
        priv: '*.*:ALL'
        state: present
        host: '%'
       
